name: flutter_bloc_timer_starter
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: 3.2.6
  flutter: 3.16.9

dependencies:
  flutter:
    sdk: flutter
  bloc: 8.1.3
  cupertino_icons: 1.0.6
  equatable: 2.0.5
  flutter_bloc: 8.1.4

dev_dependencies:
  flutter_lints: 3.0.1